import { Router } from 'express'
import multer from 'multer'
import path from 'node:path'
import crypto from 'node:crypto'
import slugify from 'slugify'
import { z } from 'zod'
import db from './db.js'
import { requireAuth, requireAdmin } from './middleware-auth.js'

const router = Router()
const upload = multer({ dest: path.resolve('uploads'), limits: { fileSize: 5 * 1024 * 1024 }, fileFilter: (_req, file, cb) => cb(null, ['image/jpeg', 'image/png', 'image/webp'].includes(file.mimetype)) })
router.use(requireAuth, requireAdmin)
const productInput = z.object({ name: z.string().min(2).optional(), description: z.string().min(2).optional(), price: z.coerce.number().int().nonnegative().optional(), salePrice: z.coerce.number().int().nonnegative().nullable().optional(), image: z.string().url().or(z.string().startsWith('/uploads/')).optional(), stock: z.coerce.number().int().nonnegative().optional(), categoryId: z.coerce.number().int().positive().nullable().optional(), sku: z.string().optional(), size: z.string().min(1).optional(), slug: z.string().min(2).optional(), lowStockThreshold: z.coerce.number().int().nonnegative().optional(), featured: z.coerce.boolean().optional(), newArrival: z.coerce.boolean().optional(), bestSeller: z.coerce.boolean().optional(), isVerified: z.coerce.boolean().optional(), isPublic: z.coerce.boolean().optional(), metaTitle: z.string().optional(), metaDescription: z.string().optional() })
const mapProduct = (row) => ({ ...row, salePrice: row.sale_price, lowStockThreshold: row.low_stock_threshold, featured: Boolean(row.featured), newArrival: Boolean(row.new_arrival), bestSeller: Boolean(row.best_seller), isVerified: Boolean(row.is_verified), isPublic: Boolean(row.is_public) })
const isProductPublishable = (product) => !!(product.name && product.description && product.price && product.image && product.categoryId && product.size && product.slug)

router.get('/dashboard', (_req, res) => res.json({ revenue: db.prepare("SELECT COALESCE(SUM(total), 0) AS value FROM orders WHERE status != 'CANCELLED'").get().value, orders: db.prepare('SELECT COUNT(*) AS value FROM orders').get().value, customers: db.prepare("SELECT COUNT(*) AS value FROM users WHERE role = 'CUSTOMER'").get().value, products: db.prepare('SELECT COUNT(*) AS value FROM products').get().value, lowStock: db.prepare('SELECT COUNT(*) AS value FROM products WHERE stock <= low_stock_threshold').get().value, pending: db.prepare("SELECT COUNT(*) AS value FROM orders WHERE status = 'PENDING'").get().value }))
router.get('/products', (_req, res) => res.json(db.prepare('SELECT p.*, c.name AS category_name FROM products p LEFT JOIN categories c ON c.id = p.category_id ORDER BY p.created_at DESC').all().map(mapProduct)))
router.post('/products', (req, res) => { const parsed = productInput.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Complete the required product fields.' }); const data = parsed.data; const normalized = { ...data, name: String(data.name || '').trim(), description: String(data.description || '').trim(), size: String(data.size || '').trim(), slug: String(data.slug || slugify(data.name || '', { lower: true, strict: true })).trim() || `${slugify((data.name || '').trim(), { lower: true, strict: true })}-${crypto.randomBytes(3).toString('hex')}` }; if (normalized.isPublic && !isProductPublishable(normalized)) return res.status(400).json({ message: 'Public products require name, description, category, image, size, price, and slug.' }); if (normalized.isPublic && !normalized.isVerified) return res.status(400).json({ message: 'Public products must be marked as verified.' }); const slug = `${slugify(normalized.name, { lower: true, strict: true })}-${crypto.randomBytes(3).toString('hex')}`; const result = db.prepare('INSERT INTO products (name, slug, description, price, sale_price, image, stock, low_stock_threshold, sku, size, category_id, featured, new_arrival, best_seller, is_verified, is_public, meta_title, meta_description, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)').run(normalized.name, normalized.slug || slug, normalized.description, normalized.price ?? 0, normalized.salePrice ?? null, normalized.image || '', normalized.stock ?? 0, normalized.lowStockThreshold ?? 5, normalized.sku || '', normalized.size || '', normalized.categoryId || null, normalized.featured ? 1 : 0, normalized.newArrival ? 1 : 0, normalized.bestSeller ? 1 : 0, normalized.isVerified ? 1 : 0, normalized.isPublic ? 1 : 0, normalized.metaTitle || '', normalized.metaDescription || ''); res.status(201).json(mapProduct(db.prepare('SELECT * FROM products WHERE id = ?').get(result.lastInsertRowid))) })
router.put('/products/:id', (req, res) => { const parsed = productInput.partial().safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Invalid product data.' }); const fields = { name: 'name', description: 'description', price: 'price', salePrice: 'sale_price', image: 'image', stock: 'stock', lowStockThreshold: 'low_stock_threshold', sku: 'sku', size: 'size', categoryId: 'category_id', featured: 'featured', newArrival: 'new_arrival', bestSeller: 'best_seller', slug: 'slug', isVerified: 'is_verified', isPublic: 'is_public', metaTitle: 'meta_title', metaDescription: 'meta_description' }; const entries = Object.entries(parsed.data); if (!entries.length) return res.status(400).json({ message: 'No changes supplied.' }); const current = db.prepare('SELECT * FROM products WHERE id = ?').get(req.params.id); if (!current) return res.status(404).json({ message: 'Product not found.' }); const merged = { ...current, ...Object.fromEntries(entries.map(([key, value]) => [key, key === 'isVerified' || key === 'isPublic' ? Boolean(value) : key === 'featured' || key === 'newArrival' || key === 'bestSeller' ? Boolean(value) : value])) }; if (merged.is_public && !isProductPublishable({ ...merged, price: merged.price ?? 0, size: merged.size || '', categoryId: merged.category_id || null, slug: merged.slug || slugify(merged.name || '', { lower: true, strict: true }), image: merged.image || '' })) return res.status(400).json({ message: 'Public products require name, description, category, image, size, price, and slug.' }); const sets = entries.map(([key]) => `${fields[key]} = ?`); const values = entries.map(([key, value]) => { if (key === 'featured' || key === 'newArrival' || key === 'bestSeller' || key === 'isVerified' || key === 'isPublic') return value ? 1 : 0; if (value === undefined || value === null) return null; return value }); values.push(req.params.id); const result = db.prepare(`UPDATE products SET ${sets.join(', ')}, updated_at = CURRENT_TIMESTAMP WHERE id = ?`).run(...values); if (!result.changes) return res.status(404).json({ message: 'Product not found.' }); res.json(mapProduct(db.prepare('SELECT * FROM products WHERE id = ?').get(req.params.id))) })
router.delete('/products/:id', (req, res) => { const result = db.prepare('DELETE FROM products WHERE id = ?').run(req.params.id); if (!result.changes) return res.status(404).json({ message: 'Product not found.' }); res.status(204).end() })
router.post('/products/:id/images', upload.single('image'), (req, res) => { if (!req.file) return res.status(400).json({ message: 'Upload a JPG, PNG, or WebP image under 5MB.' }); const url = `/uploads/${req.file.filename}`; db.prepare('INSERT INTO product_images (product_id, url, alt_text) VALUES (?, ?, ?)').run(req.params.id, url, req.body.altText || ''); db.prepare('UPDATE products SET image = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?').run(url, req.params.id); res.status(201).json({ url }) })
router.post('/inventory/:id/adjust', (req, res) => { const quantity = Number(req.body.quantity); if (!Number.isInteger(quantity) || quantity === 0) return res.status(400).json({ message: 'Enter a non-zero whole number.' }); const result = db.transaction(() => { const product = db.prepare('SELECT stock FROM products WHERE id = ?').get(req.params.id); if (!product || product.stock + quantity < 0) throw new Error('Stock cannot become negative.'); db.prepare('UPDATE products SET stock = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?').run(product.stock + quantity, req.params.id); db.prepare('INSERT INTO inventory_transactions (product_id, quantity_change, reason, created_by) VALUES (?, ?, ?, ?)').run(req.params.id, quantity, req.body.reason || 'Manual adjustment', req.user.id); return db.prepare('SELECT * FROM products WHERE id = ?').get(req.params.id) })(); res.json(mapProduct(result)) })
router.get('/orders', (_req, res) => res.json(db.prepare('SELECT o.*, COUNT(oi.id) AS item_count FROM orders o LEFT JOIN order_items oi ON oi.order_id = o.id GROUP BY o.id ORDER BY o.created_at DESC').all()))
router.get('/customers', (_req, res) => res.json(db.prepare("SELECT u.id, u.name, u.email, u.phone, u.created_at, COUNT(o.id) AS order_count, COALESCE(SUM(o.total), 0) AS total_spending FROM users u LEFT JOIN orders o ON o.user_id = u.id WHERE u.role = 'CUSTOMER' GROUP BY u.id ORDER BY u.created_at DESC").all()))
router.put('/orders/:id/status', (req, res) => { const allowed = ['PENDING', 'CONFIRMED', 'PROCESSING', 'READY_FOR_DELIVERY', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED']; if (!allowed.includes(req.body.status)) return res.status(400).json({ message: 'Invalid order status.' }); db.prepare('UPDATE orders SET status = ? WHERE id = ?').run(req.body.status, req.params.id); res.json(db.prepare('SELECT * FROM orders WHERE id = ?').get(req.params.id)) })
router.get('/categories', (_req, res) => res.json(db.prepare('SELECT * FROM categories ORDER BY name').all()))
router.post('/categories', (req, res) => { const name = String(req.body.name || '').trim(); const slug = String(req.body.slug || slugify(name, { lower: true, strict: true })).trim(); if (!name || !slug) return res.status(400).json({ message: 'Category name is required.' }); const result = db.prepare('INSERT INTO categories (name, slug, is_active) VALUES (?, ?, ?)').run(name, slug, req.body.isActive === false ? 0 : 1); res.status(201).json(db.prepare('SELECT * FROM categories WHERE id = ?').get(result.lastInsertRowid)) })
router.put('/categories/:id', (req, res) => { const current = db.prepare('SELECT * FROM categories WHERE id = ?').get(req.params.id); if (!current) return res.status(404).json({ message: 'Category not found.' }); const name = req.body.name !== undefined ? String(req.body.name).trim() : current.name; const slug = req.body.slug !== undefined ? String(req.body.slug).trim() : current.slug; const isActive = req.body.isActive === undefined ? current.is_active : (req.body.isActive ? 1 : 0); db.prepare('UPDATE categories SET name = ?, slug = ?, is_active = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?').run(name || current.name, slug || current.slug, isActive, req.params.id); res.json(db.prepare('SELECT * FROM categories WHERE id = ?').get(req.params.id)) })
router.delete('/categories/:id', (req, res) => { const result = db.prepare('DELETE FROM categories WHERE id = ?').run(req.params.id); if (!result.changes) return res.status(404).json({ message: 'Category not found.' }); res.status(204).end() })
router.get('/founder', (_req, res) => res.json(db.prepare('SELECT * FROM founder_profile WHERE id = 1').get()))
router.put('/founder', (req, res) => { const data = req.body; db.prepare('UPDATE founder_profile SET name = ?, title = ?, image = ?, bio = ?, message = ? WHERE id = 1').run(data.name || '', data.title || '', data.image || '', data.bio || '', data.message || ''); res.json(db.prepare('SELECT * FROM founder_profile WHERE id = 1').get()) })
router.post('/founder/image', upload.single('image'), (req, res) => { if (!req.file) return res.status(400).json({ message: 'Upload a JPG, PNG, or WebP image under 5MB.' }); const url = `/uploads/${req.file.filename}`; db.prepare('UPDATE founder_profile SET image = ? WHERE id = 1').run(url); res.json({ url }) })
router.get('/settings', (_req, res) => res.json(Object.fromEntries(db.prepare('SELECT key, value FROM website_settings').all().map((item) => [item.key, item.value]))))
router.put('/settings', (req, res) => { const save = db.prepare('INSERT INTO website_settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value'); db.transaction(() => Object.entries(req.body).forEach(([key, value]) => save.run(key, String(value))))(); res.json(Object.fromEntries(db.prepare('SELECT key, value FROM website_settings').all().map((item) => [item.key, item.value]))) })
router.get('/reviews', (_req, res) => res.json(db.prepare('SELECT r.*, p.name AS product_name, u.name AS customer FROM reviews r JOIN products p ON p.id = r.product_id JOIN users u ON u.id = r.user_id ORDER BY r.created_at DESC').all()))
router.put('/reviews/:id', (req, res) => { db.prepare('UPDATE reviews SET approved = ? WHERE id = ?').run(req.body.approved ? 1 : 0, req.params.id); res.json({ ok: true }) })
router.get('/coupons', (_req, res) => res.json(db.prepare('SELECT * FROM coupons ORDER BY id DESC').all()))
router.post('/coupons', (req, res) => { const data = req.body; const result = db.prepare('INSERT INTO coupons (code, type, value, minimum_order, expires_at, usage_limit, active) VALUES (?, ?, ?, ?, ?, ?, ?)').run(String(data.code).toUpperCase(), data.type, Number(data.value), Number(data.minimumOrder || 0), data.expiresAt || null, data.usageLimit ? Number(data.usageLimit) : null, data.active === false ? 0 : 1); res.status(201).json(db.prepare('SELECT * FROM coupons WHERE id = ?').get(result.lastInsertRowid)) })
router.get('/branches', (_req, res) => res.json(db.prepare('SELECT * FROM branches ORDER BY name').all()))
router.post('/branches', (req, res) => { const data = req.body; const result = db.prepare('INSERT INTO branches (name, address, phone, opening_hours, latitude, longitude, maps_url, published) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').run(data.name, data.address, data.phone || '', data.openingHours || '', data.latitude || null, data.longitude || null, data.mapsUrl || '', data.published ? 1 : 0); res.status(201).json(db.prepare('SELECT * FROM branches WHERE id = ?').get(result.lastInsertRowid)) })
export default router
